# See https://docs.codecov.io/docs/codecov-yaml
# This file is merged with the default yaml

ignore-nope:
  - "/opt/.*"
  - "/usr/.*"
  - "tests/.*"      # Ignore tests/
  - "*/*.moc"       # Ignore generated moc output

fixes:
  - "../..::"       # Go from /build-gcov/tests/ to /
