language: generic
compiler: gcc
dist: trusty

env:
  global:
    - CC="gcc-6" CXX="g++-6" #CXXFLAGS="-std=c++11 -Wall -Wno-error"
  matrix:
    - >
      QT_PPA=ppa:beineri/opt-qt-5.10.1-trusty
      QT_PKG=qt510base
      QT_SRC=/opt/qt510/bin/qt510-env.sh
  matrix-ignored:
    - >
      QT_PPA=ppa:beineri/opt-qt596-trusty
      QT_PKG=qt59base
      QT_SRC=/opt/qt59/bin/qt59-env.sh
    - >
      QT_PPA=ppa:beineri/opt-qt487-trusty
      QT_PKG=opt-libqt4-dev  
      QT_SRC=/opt/qt-4.8/bin/qt-4.8-env.sh
      CXXFLAGS="-std=c++11"

# Re Qt 4 dependencies - no finer-grained dependencies exist, sorry. See
# https://launchpadlibrarian.net/207508692/buildlog_ubuntu-trusty-amd64.opt-qt4-x11_4%3A4.8.7-0opt1_BUILDING.txt.gz

before_install:
  # g++6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # Qt
  - sudo add-apt-repository -y $QT_PPA
  - sudo apt-get -q update

install:
  # g++6
  - which gcc g++
  - sudo apt-get remove g++
  - sudo apt-get install -q g++-6
  - sudo apt autoremove
  # Qt
  - sudo apt-get install -y $QT_PKG
  # Select the compiler
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

before_script:
  - source $QT_SRC

script:
  - echo PATH=$PATH
  - $CXX --version
  - g++-6 --version
  - which qmake gcc g++
  - ln -s $(which $CC)  /home/travis/bin/gcc000
  - ln -s $(which $CXX) /home/travis/bin/g++000
  - qmake "QMAKE_CXXFLAGS+=-fprofile-arcs -ftest-coverage $CXXFLAGS" "LIBS+=-lgcov"
  - cat Makefile*
  - make
  - cd tests && make release-check debug-check

after_success:
  - >
    pwd &&
    for filename in `find .. | egrep '\.cpp'`; do
      gcov-6 -n -o . $filename > /dev/null;
    done
  - >
    bash <(curl -s https://codecov.io/bash) -e CC,QT_PPA -s tests ||
    echo "Codecov did not collect coverage reports"