language: generic
compiler: gcc
dist: trusty

env:
  global:
    - CC="gcc-6" CXX="g++-6" CXXFLAGS="-std=c++11 -Wall -Wno-error"
  matrix-ignored:
    - >
      QT_PPA=ppa:beineri/opt-qt-5.10.1-trusty
      QT_PKG=qt510base
      QT_SRC=/opt/qt510/bin/qt510-env.sh
    - >
      QT_PPA=ppa:beineri/opt-qt596-trusty
      QT_PKG=qt59base
      QT_SRC=/opt/qt59/bin/qt59-env.sh
  matrix:
    - >
      QT_PPA=ppa:beineri/opt-qt487-trusty
      QT_PKG=opt-libqt4-dev  
      QT_SRC=/opt/qt-4.8/bin/qt-4.8-env.sh

# Re Qt 4 dependencies - no finer-grained dependencies exist, sorry. See
# https://launchpadlibrarian.net/207508692/buildlog_ubuntu-trusty-amd64.opt-qt4-x11_4%3A4.8.7-0opt1_BUILDING.txt.gz

before_install:
  # g++6
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  # Qt
  - sudo add-apt-repository -y $QT_PPA
  - sudo apt-get -q update

install:
  # g++6
  - sudo apt-get remove g++
  - sudo apt-get install -q g++-6
  - sudo apt autoremove
  # Qt
  - yes | sudo apt-get install -y $QT_PKG

before_script:
  - source $QT_SRC

script:
  - echo PATH=$PATH
  - $CXX --version
  - g++-6 --version
  - which qmake
  - ln -s $(which $CC)  /home/travis/bin/gcc
  - ln -s $(which $CXX) /home/travis/bin/g++
  - qmake QMAKE_CC="$CC" QMAKE_CXX="$CXX" QMAKE_LINK="$CXX"
  - cat Makefile*
  - make
  - cd tests && make release-check debug-check
